name: Build SPClient Mod

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Build with Gradle
      run: |
        chmod +x ./gradlew
        ./gradlew build
    - name: Upload mod jar
      uses: actions/upload-artifact@v3
      with:
        name: SPClient-Mod
        path: build/libs/*.jar
